USE [ASM3_Source];
TRUNCATE TABLE [dbo].[netflix_shows]
GO

BULK INSERT [dbo].[netflix_shows]
FROM 'C:\Users\dangk\Downloads\netflix_titles.csv'
WITH (FIRSTROW = 2,  FIELDTERMINATOR = ',', ROWTERMINATOR = '0x0a')
GO

EXEC LOAD_DIM_COUNTRY;
EXEC LOAD_DIM_DIRECTOR;
EXEC LOAD_DIM_DURATION;
EXEC LOAD_DIM_RATING;
EXEC LOAD_DIM_TYPE;
EXEC Load_DIM_DATE;
EXEC Load_DIM_INFO;
EXEC Load_FACT_NETFLIX_SHOWS;